export const CART_COOKIE = 'ordercloud.cart'
export const TOKEN_COOKIE = 'ordercloud.token'
export const CUSTOMER_COOKIE = 'ordercloud.customer'
export const API_URL = 'https://sandboxapi.ordercloud.io'
export const API_VERSION = 'v1'
export const LOCALE = 'en-us'
