export { default as IconBuy } from './IconBuy'
export { default as IconSearch } from './IconSearch'
export { default as IconArrowRight } from './IconArrowRight'
export { default as IconUser } from './IconUser'
export { default as IconHistory } from './IconHistory'
export { default as IconInfo } from './IconInfo'
